config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :cohorts do
    resources :lectures
  end
  resources :students

  namespace :admin do
    resources :users do
      resources :approvals, only: [:create, :destroy]
      resources :administrator, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  validates_uniqueness_of :graduation_year
  has_many :students
  has_many :lectures
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :user
  belongs_to :cohort

  has_many :students, through: :cohort

  alias instructor user

  def start_time
    start_at.strftime("%B %-d, %Y at %-I:%M%P")
  end

  def end_time
    (start_at + duration.minutes).strftime("%B %-d, %Y at %-I:%M%P")
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort

  validates :name, presence: true, uniqueness: true
  validates :phone_number, presence: true, uniqueness: true

  # the regex matches a 10 digit number with no symbols.
  # Optional leading 1 for country code
  # Area Code cannot being with 1
  # Local Code cannot begin with 1
  validates :phone_number, format: { with: /\A1?[2-9]\d\d[2-9]\d{6}\z/, message: 'must be 10 digits only' }
  def display_number
    "#{phone_number[0..2]}-#{phone_number[3..5]}-#{phone_number[6..-1]}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:unverified, :approved, :admin]
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
  before_action :authenticate_admin!

  private

  def authenticate_admin!
    current_user.admin?
  end
end

app/controllers/admin/administrator_controller.rb
class Admin::AdministratorController < Admin::AdminController
  def create
    @user = User.find(params[:user_id])
    @user.admin!
    redirect_to admin_user_path(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    @user.approved!
    redirect_to admin_user_path(@user)
  end
end

app/controllers/admin/approvals_controller.rb
class Admin::ApprovalsController < Admin::AdminController
  def create
    @user = User.find(params[:user_id])
    @user.approved!
    redirect_to admin_user_path(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    @user.unverified!
    redirect_to admin_user_path(@user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  before_action :authenticate_admin!


  private

  def authenticate_admin!
    current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :authorize_user!
  protect_from_forgery with: :exception

  private

  def authorize_user!
    current_user && !(current_user.unverified?)
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def show
    @cohort = Cohort.find(params[:id])
  end

  def index
    @cohorts = Cohort.all
  end

  def edit
    @cohort = Cohort.find(params[:id])
  end

  def update
    @cohort = Cohort.find(params[:id])
    if @cohort.update_attributes(cohort_params)
      flash[:success] = 'Cohort updated'
      render :show
    else
      flash[:error] = @cohort.errors.full_messages.join('. ')
      render :edit
    end
  end

  def new
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.save
      flash[:success] = 'Cohort Created'
      render :show
    else
      flash[:error] = @cohort.errors.full_messages.join('. ')
      render :new
    end
  end

  private

  def cohort_params
    params.require(:cohort).permit(:graduation_year)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def show
    @lecture = Lecture.find(params[:id])
  end

  def index
    @cohort = Cohort.find(params[:cohort_id])
    @lectures = @cohort.lectures
  end

  def new
    @cohort = Cohort.find(params[:cohort_id])
    @lecture = @cohort.lectures.new
    @instructors = User.all
  end

  def create
    @cohort = Cohort.find(params[:cohort_id])
    @lecture = @cohort.lectures.new(lecture_params)
    if @lecture.save
      redirect_to cohort_lecture_path @cohort, @lecture
    else
      flash.now[:error] = @lecture.errors.full_messages.join('. ')
      render :new
    end
  end


  private

  def lecture_params
    params.require(:lecture).permit(:start_at, :duration, :user_id, :title)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show
    @student = Student.find(params[:id])
  end

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = "#{@student.name} added"
      redirect_to cohort_path @student.cohort
    else
      flash[:error] = @student.errors.full_messages.join('. ')
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(student_params)
      flash[:success] = @student.name + ' updated' 
      render :show
    else
      flash[:error] = @student.errors.full_messages.join('. ')
      render :edit
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :phone_number, :cohort_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Users (Not students)</h1>
<ul>
<% @users.each do |user| %>
  <li>
    <%= link_to "User id #{user.id}", admin_user_path(user) %>
    <%= render partial: 'admin/shared/user', locals: {user: user} %>
  </li>
<% end %>
</ul>

app/views/admin/show.html.erb
<h1>User Page</h1>
<%= render partial: 'admin/shared/user', locals: {user: @user} %>
<% if @user.unverified? %>
  <%= link_to('Approve', admin_user_approvals_path(@user), method: :post) %>
<% else %>
  <%= link_to('Revoke', admin_user_approval_path(@user), method: :delete) %>
<% end %>
<% if @user.admin? %>
  <%= link_to 'Revoke Administrator', admin_user_administrator_path(@user), method: :delete %>
<% else %>
  <%= link_to 'Make Administrator', admin_user_administrator_index_path(@user), method: :post %>
<% end %>

app/views/admin/users/index.html.erb
<h1>Users (Not students)</h1>
<ul>
<% @users.each do |user| %>
  <li>
    <%= link_to "User id #{user.id}", admin_user_path(user) %>
    <%= render partial: 'admin/users/shared/user', locals: {user: user} %>
  </li>
<% end %>
</ul>

app/views/admin/users/shared/_user.html.erb
<div>
  <div>Email: <%= user.email %></div>
  <div>Status: <%= user.role.capitalize %></div>
  <div>Last signed in: <%= user.last_sign_in_at %></div>
<div>

app/views/admin/users/show.html.erb
<h1>User Page</h1>
<%= render partial: 'admin/users/shared/user', locals: {user: @user} %>
<% if @user.unverified? %>
  <%= link_to('Approve', admin_user_approvals_path(@user), method: :post) %>
<% else %>
  <%= link_to('Revoke', admin_user_approval_path(@user), method: :delete) %>
<% end %>
<% if @user.admin? %>
  <%= link_to 'Revoke Administrator', admin_user_administrator_path(@user), method: :delete %>
<% else %>
  <%= link_to 'Make Administrator', admin_user_administrator_index_path(@user), method: :post %>
<% end %>

app/views/cohorts/edit.html.erb
<h3>Edit a Cohort</h3>
<%= form_for @cohort do |f| %>
  <%= f.label :graduation_year, 'Class of ' %>
  <%= f.text_field :graduation_year %>
  <%= f.submit %>
<% end %>

app/views/cohorts/index.html.erb
<h1>Available Cohorts</h1>
<ul>
<% @cohorts.each do |cohort| %>
  <li><%= link_to "Class of #{cohort.graduation_year}", cohort_path(cohort) %></li>
<% end %>
</ul>

app/views/cohorts/new.html.erb
<h3>Create a new Cohort</h3>
<%= form_for @cohort do |f| %>
  <%= f.label :graduation_year, 'Class of ' %>
  <%= f.text_field :graduation_year %>
  <%= f.submit %>
<% end %>

app/views/cohorts/show.html.erb
<h3>Year of Graduation: <%= @cohort.graduation_year %></h3>
<%= link_to 'Add new student', new_student_path %>
<%= link_to 'Schedule a lecture', new_cohort_lecture_path(@cohort.id) %>
<ul>
<% @cohort.students.each do |student| %>
  <li><%= link_to student.name, student_path(student) %></li>
<% end %>
</ul>

app/views/home/index.html.erb
<ul>
  <li><%= link_to 'Cohorts', cohorts_path %></li>
  <li><%= link_to 'Students', students_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feedback</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lectures/index.html.erb
<h1>Lectures for <%= @cohort %></h1>
<ul>
  <% @lectures.each do |lecture| %>
    <li><%= link_to "#{lecture.title}: #{lecture.start_time}", cohort_lecture_path(@cohort, lecture) %></li>
  <% end %>
</ul>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>
<%= form_for [:cohort, @lecture] do |f| %>
  <%= f.label 'Title' %>
  <%= f.text_field :title %><br />
  <%= f.label 'Start Time' %>
  <%= f.datetime_field :start_at %><br />
  <%= f.label :duration %>
  <%= f.text_field :duration %> minutes<br />
  <%= f.collection_select :user_id, @instructors, :id, :email %> <br />
  <%= f.submit %>
<% end %>

app/views/lectures/show.html.erb
<h1>Lecture</h1>
<ul>
  <li><%= @lecture.title %></li>
  <li>Lecture begins: <%= @lecture.start_time %></li>
  <li>Lecture ends: <%= @lecture.end_time %></li>
</ul>

app/views/students/_form.html.erb
<%= form_for student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %><br>
  <%= f.label 'Class of ' %>
  <%= f.collection_select :cohort_id, Cohort.all, :id, :graduation_year %><br>
  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h3>Edit Student</h3>
<%= render partial: 'form', locals:  { student: @student } %>

app/views/students/index.html.erb
<h1>Student Directory</h1>
<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.name, student_path(student.id) %></li>
  <% end %>
</ul>

app/views/students/new.html.erb
<h3>Add Student</h3>
<%= render partial: 'form', locals:  { student: @student } %>

app/views/students/show.html.erb
<h3><%= @student.name %></h3>
<ul>
  <li><%= link_to "Class of #{@student.cohort.graduation_year}", cohort_path(@student.cohort) %></li>
  <li><%= @student.display_number %></li>
</ul>
<%= link_to 'Edit', edit_student_path(@student.id) %>